CONDAENVNAME: transformers-torch-19
DESCRIPTION: A hate detection model for tweets in portuguese
ENVPREFIX: dev
KEYVAULTNAME: aftmlws018192439893
LOCATION: uksouth
MODELNAME: hate-pt-speech
RESOURCEGROUPNAME: AFT-ML-01
STORAGEACCOUNTNAME: aftmlstorage
WORKSPACENAME: AFT-ML-WS-01
