name: workspace-CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .aml/data/**
      - .cloud/**

jobs:
  deployment:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logining in into Azure
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: ./.github/actions/azure-arm-template-deployment
        name: Workspaces - Deploying resources
        with:
          resourceGroup: ${RESOURCEGROUPNAME}
          location: ${LOCATION}
          deploymentName: aml-deployment
          templateFile: .cloud/templates/deploy.json
          parameters: .cloud/${ENVPREFIX}/deploy.parameters.json computeAdminUserName=${{ secrets.COMPUTEADMINUSERNAME }} computeAdminUserPassword=${{ secrets.COMPUTEADMINUSERPASSWORD }} datasetsClientId=${{ secrets.DATASETSCLIENTID }} datasetsClientSecret=${{ secrets.DATASETSCLIENTSECRET }} secretsManagementObjectId=${{ secrets.AUTOMATION_OBJECT_ID }}

      - id: datasets_init
        name: Workspaces - Datasets initialization
        uses: ./.github/actions/aml-dataset-create
        with:
          datasetFile: .aml/data/*/dataset.yml
          initialize: true
          initialDataPath: sample
          storageAccount: ${STORAGEACCOUNTNAME}
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
